CREATE TABLE ADMIN (
    ID  BIGINT(38) AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR(10) NOT NULL,
    SENHA VARCHAR(15) NOT NULL
 );

CREATE TABLE CADASTRO (
    ID  BIGINT(38) AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(30) NOT NULL,
    TELEFONE  BIGINT(11) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    CEP  BIGINT(8) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(2) NOT NULL,
    DESCRICAO VARCHAR(150) NOT NULL,
    CATEGORIA VARCHAR(100) NOT NULL
);